- name: create repos dir
  file:
    path: "{{ homedir }}/gits"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

# from develop
- name: create fish config dir
  file:
    path: "{{ homedir }}/.config/fish"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: deploy config.fish
  template:
    src: "config.fish.j2"
    dest: "{{ homedir }}/.config/fish/config.fish"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0655

- name: deploy .tmux.conf
  copy:
    src: ".tmux.conf"
    dest: "{{ homedir }}/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0655

# from kemacs
# - name: delete kemacs repo
#   file:
#     path: "{{ homedir }}/gits/kemacs"
#     state: absent

# - name: clone kemacs repo
#   become_user: "{{ user }}"
#   shell: "git clone https://github.com/keiSunagawa/kemacs.git ~/gits/kemacs"
#   environment:
#       PATH: "{{ homedir }}/.nix-profile/bin/:{{ ansible_env.PATH }}"

# - name: deploy .emacs.d
#   become_user: "{{ user }}"
#   file:
#     src: "{{ homedir }}/gits/kemacs/.emacs.d"
#     dest: "{{ homedir }}/.emacs.d"
#     state: link
#     force: true
