version: 2

references:
  commands:
    functions: &functions
      name: Setup AWS
      command: |
        cat << EOS > functions
        f() {
          echo \$1
        }
        EOS

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/develop
    steps:
      - checkout
      - run: *functions
      - run:
          name: main
          command: |
            . functions
            f 'first ci'
